services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    whatwedo\MonitoringBundle\:
        resource: '../../{Controller,Command,Manager}'

    whatwedo\MonitoringBundle\Check\:
        resource: '../../Check/*'
        calls:
            - [ setContainer, [ '@service_container' ]]